### ISSUE TITLE
Applet fails under Debian

### ISSUE THREAD

**Issue by karlsackett** [Kilian/f.lux-indicator-applet#14]
Apparently the applet requires a python-appindicator package, which isn't available for Debian.

```
miranda$ ./fluxgui 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/fluxgui/fluxgui.py", line 2, in <module>
    import appindicator
ImportError: No module named appindicator
```

**Comment by willotter** [comment]
For reference in case anyone wants to get this working on Debian. `python-appindicator` is now available in Debian. If you follow this guide to create the package from source (https://wiki.debian.org/CreatePackageFromPPA) you can install fluxgui. For reference I am running Debian Testing (Stretch) currently but looks like it should work from wheezy upwards.
