### ISSUE TITLE
PPA needs the multi-monitor update

### ISSUE THREAD

**Issue by Beanow** [Kilian/f.lux-indicator-applet#46]
https://launchpad.net/~kilian/+archive/ubuntu/f.lux
Sports a 2013-11-29 version. Which did not yet support multi-monitor.

**Comment by HeroCC** [comment]
Same here, please update! The guide @HauRuck linked is down for me, and I prefer to use PPAs. Please update fast!

**Comment by jalcine** [comment]
Easiest route is to have a contributor update packaging for the desired platforms and then have those built. I'm familiar with packaging but it'll take me a while to get started.
