### ISSUE TITLE
Typo with the word "lighting"

### ISSUE THREAD

**Issue by hukkinj1** [Kilian/f.lux-indicator-applet#54]
The word "lighting" is spelled "lightning" in applet preferences: "Better lightning for your computer". The same typo also exist in the description of the GitHub page:  "Better lightning for Ubuntu http://stereopsis.com/flux/linux.html".

Software version: fluxgui 1.1.8

**Comment by marcopierobon** [comment]
The preference in the last build is correctly spelled, and the mentioned text is not on the page anymore. Can the issues be closed?

**Comment by hukkinj1** [comment]
The description of the GItHub page (https://github.com/Kilian/f.lux-indicator-applet) still has the word misspelled.
