### ISSUE TITLE
[UBUNTU] Only works on 1 screen the other remains the same.

### ISSUE THREAD

**Issue by bweston92** [Kilian/f.lux-indicator-applet#65]

**Comment by scorpjio** [comment]
I have this problem too

**Comment by synthor** [comment]
Which hardware, which driver, X11 settings?

No problem here with AMD/Nvidia with propritary driver. I never tried f.lux with Nouveau or the RadeonDriver.

Only on my workstation in the office with two AMD cards, fglrx and Xinerana enabled f.lux doesn't work on all screens..without Xinerama it works.

**Comment by Kilian** [comment]
@synthor It could be related to the version of xflux installed. Manually installing a newer version by replacing the one in /usr/bin (as mentioned in #57) should help.

**Comment by synthor** [comment]
Thx for the info, I'll check that tomorrow in the morning and provide feedback.

**Comment by synthor** [comment]
Negative. I already have the 706kB, created 2013-09-27 01:42:30, on my workstation here in the office.

This machine here is a Debian 8.3 x64 with XFCE 4.10 and not Xubuntu...
