### ISSUE TITLE
high cpu usage for fluxgui

### ISSUE THREAD

**Issue by lofidevops** [Kilian/f.lux-indicator-applet#7]
My system occasionally slows down with fluxgui using lots of CPU. This is during the day, so the screen temperature is not being changed.

I'm running latest PPA version on Natty. Any debug info I can provide?

**Comment by timoc** [comment]
I was about to suggest this. There is a kde plasmoid for it, which does not work so well, but redshift seems to.

**Comment by dmays** [comment]
Experiencing this on Ubuntu 14.04 64-bit.  Surprised @herf hasn't responded here or fixed this in nearly 4 years.

**Comment by herf** [comment]
Basically every bug people currently is due to us doing a very-rough IPC over stdin/stdout. The daemon is pretty reliable running on its own. Currently when one side or the other sends too much data (bigger than the normal backlog) the communication channel either jams up (resulting in no changes after that) or winds up in a spinlock (which is worse and results in the 100% cpu issue).

I have a better version I made for our nascent Android build, based on Linux abstract sockets (didn't do dbus because it's not on all distros). Can backport it if someone wants to take on the GUI-side work.

**Comment by Kilian** [comment]
I would love to go a GUI rewrite in something like nw.js, atom or thrust, split of the GUI and the control API into separate components.

**Comment by Horlacher** [comment]
Same problem here with F.Lux on Ubuntu 14.04 64-bit and with previous versions. Fluxgui sporadically ate up my battery and I can confirm the relation to the suspend mode.

After a year I had to switch back to [Redshift](https://apps.ubuntu.com/cat/applications/gtk-redshift/) which is stable. If you want to change the color tone, the location provider or other settings, check the Configuration file explanation/example on the [Redshift website](http://jonls.dk/redshift/).

**Comment by stuaxo** [comment]
@herf in the meantime, where is the shonky IPC over a pipe ?

**Comment by raywillis** [comment]
I found that xflux was using CPU 3 and 4 up to 100% alternately. This was really heating up my Lenovo x220i laptop. The fan was on 100%. I learned that heat can damage Li ion batteries. So I killed the xflux process and it stopped the heating. My advice is to uninstall f.lux.

**Comment by roipoussiere** [comment]
Same error using Awesome window manager. I switched to Redshift as suggested @socketubs.

**Comment by dawid2193487** [comment]
5 years

still not fixed

what the fuck f.lux.

**Comment by stuaxo** [comment]
@ca1ek Open source takes a long time, like waiting for a good wine.  (Mostly because ${PROJECT_YOU_LIKE_TO_USE} has far less people working on it than you'd imagine, and even less with the time to fix bugs.

**Comment by dawid2193487** [comment]
I do understand, but 5 years for such an obnoxious bug is a lot too much. I don't really care by now, I switched to redshift.

**Comment by stuaxo** [comment]
I also switched to redshift, which has it's own problems.   Had a a lot of time last year to dive in and fix problems on open source projects, and it does indeed take quite a bit of time to investigate and fix these things, hence most things are broken in software :/
