### ISSUE TITLE
Gradually stops

### ISSUE THREAD

**Issue by SergioReis97** [Kilian/f.lux-indicator-applet#79]
As I run f.lux indicator my screen colors do go down, and if i do a preview it does turn on but.. after X seconds (not the preview, the actual applet) stops working. I need to pause and unpause wich isn't really something that is ok to do every 10 seconds or so...
Linux Mint 18.1

**Comment by Kilian** [comment]
This repoitory is unmaintained. Please mention any issues in https://github.com/xflux-gui/xflux-gui
